
INSERT INTO	Types
			(Type,							Kind			)
VALUES		('LEADER_MICO_BOWSER',			'KIND_LEADER'	),
			('LEADER_MICO_PEACH',			'KIND_LEADER'	),
			('LEADER_MICO_DAISY',			'KIND_LEADER'	);
		

INSERT INTO	Leaders
			(LeaderType,					Name,									InheritFrom,		SceneLayers,	Sex)
VALUES		('LEADER_MICO_BOWSER',			'LOC_LEADER_MICO_BOWSER_NAME',			'LEADER_DEFAULT', 	4,				'Male'),
			('LEADER_MICO_PEACH',			'LOC_LEADER_MICO_PEACH_NAME',			'LEADER_DEFAULT', 	4,				'Female'),
			('LEADER_MICO_DAISY',			'LOC_LEADER_MICO_DAISY_NAME',			'LEADER_DEFAULT', 	4,				'Female');



INSERT INTO	CivilizationLeaders
			(CivilizationType,				LeaderType,						CapitalName							)
VALUES		('CIVILIZATION_MICO_KOOPA',		'LEADER_MICO_BOWSER',			'LOC_CITY_NAME_MICO_KOOPA_1'		),
			('CIVILIZATION_MICO_MUSHROOM',	'LEADER_MICO_PEACH',			'LOC_CITY_NAME_MICO_MUSHROOM_1'		),
			('CIVILIZATION_MICO_SARASALAND','LEADER_MICO_DAISY',			'LOC_CITY_NAME_MICO_SARASALAND_1'	);
		

INSERT INTO	LeaderQuotes
			(LeaderType,					Quote										)
VALUES		('LEADER_MICO_BOWSER',			'LOC_PEDIA_LEADERS_PAGE_MICO_BOWSER_QUOTE'	),
			('LEADER_MICO_PEACH',			'LOC_PEDIA_LEADERS_PAGE_MICO_PEACH_QUOTE'	),
			('LEADER_MICO_DAISY',			'LOC_PEDIA_LEADERS_PAGE_MICO_DAISY_QUOTE'	);
